---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalsg/marvin

inputs:
  - name: marvin-source
  - name: marvin-docker-image

outputs:
  - name: marvin-release

run:
  path: marvin-source/ci/tasks/unit.sh
