---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: marvin-build-docker-image

inputs:
  - name: marvin-source
  - name: marvin-build-docker-image

outputs:
  - name: marvin-release

run:
  path: marvin-source/ci/tasks/unit.sh
