---
resources:
- name: marvin-source
  type: git
  source:
    uri: https://github.com/pivotal-sg/marvin-bot.git
- name: milliways-source
  type: git
  source:
    uri: https://github.com/pivotal-sg/milliways.git

jobs:
- name: unit
  public: true
  plan:
  - get: marvin-source
    trigger: true
  - task: marvin-unit-test
    file: marvin-source/ci/tasks/unit.yml
- name: integration
  public: true
  plan:
  - get: milliways-source
    trigger: true
  - task: marvin-integration-test
    file: milliways-source/ci/tasks/integration.yml
