---
resources:
- name: marvin-source
  type: git
  source:
    uri: https://github.com/pivotal-sg/marvin-bot.git

jobs:
- name: unit
  public: true
  plan:
  - get: marvin-source
    trigger: true
  - task: marvin-unit-test
    file: marvin-source/ci/tasks/unit.yml
