---
resources:
- name: marvin-source
  type: git
  source:
    uri: https://github.com/pivotal-sg/marvin-bot.git
- name: milliways-source
  type: git
  source:
    uri: https://github.com/pivotal-sg/milliways.git
- name: marvin-release
  type: github-release
  source:
    user: pivotal-sg
    repository: marvin-bot
    access_token: {{GIT_ACCESS_TOKEN}}

jobs:
- name: unit
  public: true
  plan:
  - get: marvin-source
    trigger: true
  - task: marvin-unit-test
    file: marvin-source/ci/tasks/unit.yml
  - put: marvin-release
    params:
      name: marvin-release/release-tag
      tag: marvin-release/release-tag
      globs:
        - marvin-release/marvin-0.0.1-SNAPSHOT.jar

- name: integration
  public: true
  plan:
    - aggregate:
      - get: milliways-source
        trigger: true
      - get: marvin-release
        trigger: true
        passed: [unit]
    - task: marvin-integration-test
      file: milliways-source/ci/tasks/integration.yml
