---
resources:
- name: marvin-source
  type: git
  source:
    uri: https://github.com/pivotal-sg/marvin-bot.git
- name: milliways-source
  type: git
  source:
    uri: https://github.com/pivotal-sg/milliways.git
- name: marvin-release
  type: github-release
  source:
    user: alanyjw
    repository: https://github.com/pivotal-sg/marvin-bot.git

jobs:
- name: unit
  public: true
  plan:
  - get: marvin-source
    trigger: true
  - task: marvin-unit-test
    file: marvin-source/ci/tasks/unit.yml
  - put: marvin-release
    params:
      name: marvin-source/build/libs/*.jar
      tag: marvin-source/build/libs/release-tag

- name: integration
  public: true
  plan:
    - aggregate:
      - get: milliways-source
        trigger: true
      - get: marvin-release
        trigger: true
        passed: [unit]
    - task: marvin-integration-test
      file: milliways-source/ci/tasks/integration.yml
